
spring:
  application:
    name: eureka-server
    
server:
  port: 2002
  
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: eureka2
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url: 
      defaultZone: http://eureka1:2001/eureka  #eureka2启动时向eureka1注册
